/**
 * API distritiendamj
 * Documentación Api distritiendamj
 *
 * OpenAPI spec version: v1
 * Contact: wilson.199819@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Carteras {
    'id'?: number;
    'fechaFacturacion'?: Date;
    'fechaVencimiento': string;
    'pago'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "fechaFacturacion",
            "baseName": "fecha_facturacion",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "fechaVencimiento",
            "baseName": "fecha_vencimiento",
            "type": "string",
            "format": "date"
        },
        {
            "name": "pago",
            "baseName": "pago",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Carteras.attributeTypeMap;
    }

    public constructor() {
    }
}

