/**
 * API distritiendamj
 * Documentación Api distritiendamj
 *
 * OpenAPI spec version: v1
 * Contact: wilson.199819@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FacturaCompras } from '../models/FacturaCompras';
import { HttpFile } from '../http/http';

export class DetalleCompras {
    'id'?: number;
    'facturaCompra'?: number | null;
    'fcompraData'?: FacturaCompras;
    'productoCompra'?: number | null;
    'cantidad'?: number | null;
    'precioUnitario'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "facturaCompra",
            "baseName": "factura_compra",
            "type": "number",
            "format": ""
        },
        {
            "name": "fcompraData",
            "baseName": "fcompra_data",
            "type": "FacturaCompras",
            "format": ""
        },
        {
            "name": "productoCompra",
            "baseName": "producto_compra",
            "type": "number",
            "format": ""
        },
        {
            "name": "cantidad",
            "baseName": "cantidad",
            "type": "number",
            "format": ""
        },
        {
            "name": "precioUnitario",
            "baseName": "precio_unitario",
            "type": "string",
            "format": "decimal"
        }    ];

    static getAttributeTypeMap() {
        return DetalleCompras.attributeTypeMap;
    }

    public constructor() {
    }
}

