/**
 * API distritiendamj
 * Documentación Api distritiendamj
 *
 * OpenAPI spec version: v1
 * Contact: wilson.199819@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DetalleVentas {
    'id'?: number;
    'facturaVenta'?: number | null;
    'productoVenta'?: number | null;
    'cantidad'?: number | null;
    'precioProducto'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "facturaVenta",
            "baseName": "factura_venta",
            "type": "number",
            "format": ""
        },
        {
            "name": "productoVenta",
            "baseName": "producto_venta",
            "type": "number",
            "format": ""
        },
        {
            "name": "cantidad",
            "baseName": "cantidad",
            "type": "number",
            "format": ""
        },
        {
            "name": "precioProducto",
            "baseName": "precio_producto",
            "type": "string",
            "format": "decimal"
        }    ];

    static getAttributeTypeMap() {
        return DetalleVentas.attributeTypeMap;
    }

    public constructor() {
    }
}

