/**
 * API distritiendamj
 * Documentación Api distritiendamj
 *
 * OpenAPI spec version: v1
 * Contact: wilson.199819@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FacturaVCarteras {
    'id'?: number;
    'facturaVenta'?: number | null;
    'cartera'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "facturaVenta",
            "baseName": "factura_venta",
            "type": "number",
            "format": ""
        },
        {
            "name": "cartera",
            "baseName": "cartera",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FacturaVCarteras.attributeTypeMap;
    }

    public constructor() {
    }
}

