/**
 * API distritiendamj
 * Documentación Api distritiendamj
 *
 * OpenAPI spec version: v1
 * Contact: wilson.199819@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FacturaVentas {
    'id'?: number;
    'fechaIngreso'?: Date;
    'clienteF'?: number | null;
    'totalV'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "fechaIngreso",
            "baseName": "fecha_ingreso",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "clienteF",
            "baseName": "cliente_f",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalV",
            "baseName": "total_v",
            "type": "string",
            "format": "decimal"
        }    ];

    static getAttributeTypeMap() {
        return FacturaVentas.attributeTypeMap;
    }

    public constructor() {
    }
}

