/**
 * API distritiendamj
 * Documentación Api distritiendamj
 *
 * OpenAPI spec version: v1
 * Contact: wilson.199819@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Lotes {
    'id'?: number;
    'fechaIngreso'?: Date;
    'productoLote'?: number | null;
    'cantidad'?: string | null;
    'numeroLote'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "fechaIngreso",
            "baseName": "fecha_ingreso",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "productoLote",
            "baseName": "producto_lote",
            "type": "number",
            "format": ""
        },
        {
            "name": "cantidad",
            "baseName": "cantidad",
            "type": "string",
            "format": "decimal"
        },
        {
            "name": "numeroLote",
            "baseName": "numero_lote",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Lotes.attributeTypeMap;
    }

    public constructor() {
    }
}

