/**
 * API distritiendamj
 * Documentación Api distritiendamj
 *
 * OpenAPI spec version: v1
 * Contact: wilson.199819@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Pagos {
    'id'?: number;
    'medioPago': PagosMedioPagoEnum;
    'estadoPago': PagosEstadoPagoEnum;
    'facturaV'?: number | null;
    'facturaC'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "medioPago",
            "baseName": "medio_pago",
            "type": "PagosMedioPagoEnum",
            "format": ""
        },
        {
            "name": "estadoPago",
            "baseName": "estado_pago",
            "type": "PagosEstadoPagoEnum",
            "format": ""
        },
        {
            "name": "facturaV",
            "baseName": "factura_v",
            "type": "number",
            "format": ""
        },
        {
            "name": "facturaC",
            "baseName": "factura_c",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Pagos.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PagosMedioPagoEnum {
    Efectivo = 'Efectivo',
    TarjetaDeCrdito = 'Tarjeta de Crédito',
    TransferenciaBancaria = 'Transferencia Bancaria'
}
export enum PagosEstadoPagoEnum {
    Pendiente = 'PENDIENTE',
    Aprobado = 'APROBADO',
    Rechazado = 'RECHAZADO'
}

