/**
 * API distritiendamj
 * Documentación Api distritiendamj
 *
 * OpenAPI spec version: v1
 * Contact: wilson.199819@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Stock {
    'id'?: number;
    'productoStock'?: number | null;
    'cantidad'?: number | null;
    'loteStock'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "productoStock",
            "baseName": "producto_stock",
            "type": "number",
            "format": ""
        },
        {
            "name": "cantidad",
            "baseName": "cantidad",
            "type": "number",
            "format": ""
        },
        {
            "name": "loteStock",
            "baseName": "lote_stock",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Stock.attributeTypeMap;
    }

    public constructor() {
    }
}

